♻️ Initial Refactor commit [APP-687]
elementor/one-click-accessibility pull request #109
Opened 2024-10-20 10:32 UTC by bainternet

Added new code base with namespace helper classes and utils.

2024-10-23 12:43 UTC, nirbhayel commented on .github/scripts/update-version-in-files.js
> +		await replaceInFileWithArray( './image-optimization.php',
Looks like file referred is incorrect

2024-10-23 12:46 UTC, nirbhayel commented on .github/scripts/update-version-in-files.js
> +					to: `define( 'IMAGE_OPTIMIZER_VERSION', '${ VERSION }' );`,
incorrect constant name

2024-10-23 12:48 UTC, nirbhayel commented on tests/phpunit/helpers/test-base.php
> +namespace SiteMailer\Tests\Helpers;
incorrect namespace

2024-10-23 12:49 UTC, nirbhayel commented on .github/scripts/update-version-in-files.js
> +		await replaceInFileWithArray( './image-optimization.php',
incorrect file name

2024-10-23 12:49 UTC, nirbhayel reviewed
Please check comments

2024-10-24 22:31 UTC, pkniazevych commented on classes/utils/assets.php
> +		return empty( $version ) ? \SITE_MAILER_VERSION : $version;
Let's to update the name

2024-10-24 22:31 UTC, pkniazevych commented on classes/utils/assets.php
> +		//return \SITE_MAILER_ASSETS_URL . $asset_type . '/' . ( '' === $suffix ? 'dev/' : '' ) . $asset_name . $suffix . '.' . $asset_type;
```suggestion
```

2024-10-24 22:32 UTC, pkniazevych commented on classes/utils/assets.php
> +		$url = \SITE_MAILER_ASSETS_URL . 'build/';
Let's update those also

2024-10-24 22:32 UTC, pkniazevych commented on classes/utils/assets.php
> +		$css_version = ( defined( 'SCRIPT_DEBUG' ) && SCRIPT_DEBUG ) ? filemtime( $dir . $css_file_name ) : \SITE_MAILER_VERSION;
And here

2024-10-24 22:35 UTC, pkniazevych commented on ruleset.xml
> +	<config name="text_domain" value="site-mailer" />
Let's update the text domain

2024-10-24 22:37 UTC, pkniazevych commented on classes/utils/assets.php
> +		return \SITE_MAILER_ASSETS_URL . '/build/' . $asset_name . $suffix . '.' . $asset_type;
Let's update `SITE_MAILER_ASSETS_URL`

2024-10-24 22:38 UTC, pkniazevych requested changes
Please, check the comments.

2024-10-29 19:13 UTC, DinetsV approved these changes

2024-10-29 19:13 UTC, DinetsV commented on classes/logger.php
> +			$message = '[Site Mailer]: ' . $log_level . ' in ' . "$class$type$function()" . ': ' . $message;
```suggestion
			$message = '[One Click Accessibility]: ' . $log_level . ' in ' . "$class$type$function()" . ': ' . $message;
```

2024-10-29 19:13 UTC, DinetsV commented on classes/logger.php
> +			$message = '[Site Mailer]: ' . $log_level . ' in ' . "$function()" . ': ' . $message;
```suggestion
			$message = '[One Click Accessibility]: ' . $log_level . ' in ' . "$function()" . ': ' . $message;
```

2024-11-05 12:06 UTC, merged