[APP 707] general setting components
elementor/one-click-accessibility pull request #113
Opened 2024-11-04 11:42 UTC by nirbhayel

2024-11-14 07:56 UTC, bainternet commented on modules/settings/assets/js/components/color-picker/style.css
> +.custom-color-picker.react-colorful {
```suggestion
.widget-settings-color-picker.react-colorful {
```

let give it a more specific class then just "custom-color-picker"

2024-11-14 07:59 UTC, bainternet requested changes
please see comment above and are we sure that this is RTL ready??

2024-11-16 13:57 UTC, bainternet approved these changes

2024-11-16 13:58 UTC, bainternet commented on modules/settings/assets/js/components/color-picker/style.css
you only changed the first one!

what about the rest of `.custom-color-picker`?

2024-11-16 13:59 UTC, bainternet requested changes
please update styles

2024-11-18 08:41 UTC, nirbhayel commented on modules/settings/assets/js/components/color-picker/style.css
updated

2024-11-20 09:11 UTC, merged