Feature/app 810 assemble icon settings page
elementor/one-click-accessibility pull request #117
Opened 2024-11-29 12:22 UTC by nirbhayel

2024-11-29 14:45 UTC, DinetsV commented on modules/settings/assets/js/components/bottom-bar/index.js
> +			try {
Use async/await with try-catch or then/catch

2024-12-01 00:28 UTC, pkniazevych requested changes
Please, check Vasyl's comments

2024-12-02 05:54 UTC, nirbhayel commented on modules/settings/assets/js/app.js
> +	useSavedSettings();
yes, it loads up the saved settings for icon design

2024-12-02 09:16 UTC, nirbhayel commented on modules/settings/assets/js/components/index.js
> +export { default as BottomBar } from './bottom-bar';
It is based on the previous ones we used and to keep them the same as per the last discussion.

2024-12-02 11:21 UTC, nirbhayel commented on modules/settings/assets/js/components/bottom-bar/index.js
> +			try {
added

2024-12-02 11:35 UTC, nirbhayel commented on modules/settings/assets/js/helpers/accessibility-options.js
> +	const optionStyle = {
updated

2024-12-03 09:19 UTC, DinetsV commented on modules/settings/assets/js/components/index.js
> +export { default as BottomBar } from './bottom-bar';
Ok but by default IDE import without "default" and I'm not sure that we have any rules for this

2024-12-03 09:42 UTC, DinetsV commented on modules/settings/assets/js/components/index.js
> +export { default as BottomBar } from './bottom-bar';
Sorry I missed that it's an export

2024-12-03 09:50 UTC, DinetsV approved these changes

2024-12-03 09:50 UTC, DinetsV commented on modules/settings/assets/js/components/bottom-bar/index.js
> +				});
You dont need to use then after await just use 
```suggestion
        await save({
					a11y_widget_icon_settings: {
						style: iconDesign,
						position: iconPosition,
					},
				});
	success('Settings saved!');
	setHasChanges(false);
```

2024-12-03 09:50 UTC, DinetsV commented on modules/settings/assets/js/app.js
> +	useSavedSettings();
Move call before initialize constants 
```suggestion
        useSavedSettings();
        const { isConnected } = usePluginSettingsContext();
	const { notificationMessage, notificationType } = useNotificationSettings();
	const { selectedMenu } = useSettings();
```

2024-12-03 14:12 UTC, bainternet approved these changes

2024-12-04 06:03 UTC, merged